### ISSUE TITLE
Very few reads can be mapped

### ISSUE THREAD

**Issue by YaohuaYangVEC** [motu-tool/mOTUs_v2#29]
Dear mOTUs2 developers:

Currently I've been trying to use mOTUs2 for microbial profiling of my own oral shotgun metagenomic sequencing data. It's very wired that for all my samples (~300), only very few reads could be mapped. For example, for a sample with ~200,0000, only ~300 reads could be mapped to the reference. My command line is as followings:

motus profile -f sample1_1.fastq.gz -r sample1_2.fastq.gz -t 16 -o SW60252.profile -c -q -n sample1 -y insert.raw_counts

Would you please help me out?

Thanks a lot!

Yaohua

**Comment by YaohuaYangVEC** [comment]
To make it more specific:

For example, for a sample with ~200,0000 **non-human reads**, only ~300 reads could be mapped to the reference. 

Yaohua

**Comment by AlessioMilanese** [comment]
Hi @YaohuaYangVEC,

I'm happy to hear that you are interested in using mOTUs2. So first I can suggest you to read [here](https://github.com/motu-tool/mOTUs_v2/wiki/FAQ#1-why-just-few-reads-map-in-my-profiles).

Second, can I ask you to send me the resulting profile of one or two samples so that I can have a look?

Cheers,
alessio

**Comment by YaohuaYangVEC** [comment]
Hi Alessio,

Thank you so much for this quick response!

But the problems I met are probably not from the tips you pointed out in the FAQ. Please see below:

1. The mOTUs profiler is filtering out all the reads that map with less than 75 nucleotides (-l 75). For example, with old samples, the fastq reads were on average of length 50, and in this case they would all be filtered out. **For all of my data of ~300 samples, the reads are **150bp** paired-end.** 
2. The biomes that we can currently profile with meta-mOTUs (unknown species) are oceans, human gut, human oral cavity, human vagina and human skin.  **My data are from human mouth wash samples, hence the microbiomes of my samples should belong to human oral cavity. In addition, human reads were removed before running motus2.**

I also tried to using motus2 on an oral sample and a gut sample downloaded from HMP: http://downloads.hmpdacc.org/dacc/hhs/genome/microbiome/wgs/analysis/hmwgsqc/v1/SRS015985.tar.bz2 (oral); http://downloads.hmpdacc.org/data/Illumina/HMDEMO/SRP002468/affected/SRS267354.tar.bz2 (gut). However, similarly, very few reads could be mapped. Please see the attached files "hmp_oral.xls" and "hmp_gut.xls".

Attached please also find the profiles generated by motus2 for 2 of my samples. Originally, the "mothwash1" has 1,684,987 non-human reads and "mouthwash2" has 27,888,823 non-huaman reads.

[hmp_oral.xlsx](https://github.com/motu-tool/mOTUs_v2/files/3452766/hmp_oral.xlsx)
[hmp_gut.xls.xlsx](https://github.com/motu-tool/mOTUs_v2/files/3452767/hmp_gut.xls.xlsx)
[mouthwash1..xlsx](https://github.com/motu-tool/mOTUs_v2/files/3452768/mouthwash1.xlsx)
[nouthwash2.xlsx](https://github.com/motu-tool/mOTUs_v2/files/3452769/nouthwash2.xlsx)

**Comment by YaohuaYangVEC** [comment]
Hi Alessio,

I'm sorry that I gave you so many details but I meant to make sure I described the issues specifically.

Thank you again for your patience!!

Best,
Yaohua

**Comment by AlessioMilanese** [comment]
No problem,
I see in mouthwash2 that there are 15,615 reads mapping, of which
- 12,061 map to ref-mOTUs (77%)
- 1,860 map to meta-mOTUs (11%)
- 1,694 map to -1 (12%)
This is more or less in line with what we see for our data (see [here](https://www.nature.com/articles/s41467-019-08844-4/figures/1))

For mouthwash1, there are 372 reads in total:
- 305 map to ref-mOTUs
- 25 map to meta-mOTUs
- 42 map to -1

The proportions are still similar to expected.

I think that the main problem for mouthwash1 is that there are not many reads to start with. I would probably discard this sample because there are not enough reads.
What you can do is to use `-g 1` and you will have more sensitivity, but also more false positives. Check https://github.com/motu-tool/mOTUs_v2/wiki/Increase-precision-or-recall

**Comment by YaohuaYangVEC** [comment]
Thanks for this quick response.

Do you think ~0.055% of mapped reads for mouthwash2 and ~0.022% of mapped reads for mouthwash1 are acceptable? These will mean that nearly all of reads are discarded. And statistically, such low proportion may be treated as random errors. This is my naive opinion. 

Thanks!!

Yaohua

**Comment by AlessioMilanese** [comment]
> Do you think ~0.055% of mapped reads for mouthwash2 and ~0.022% of mapped reads for mouthwash1 are acceptable? These will mean that nearly all of reads are discarded.

Many of the reads are not used for profiling, it's correct.
Maybe another thing to consider: did you remove human reads?

> And statistically, such low proportion may be treated as random errors.

We don't take random reads, we map all of the reads to 10 single-copy protein-coding marker genes; and we filter them based on how good they map. The measure that you get at the end represents an estimation of the prokaryotic cell counts in your sample.
Looking at simulated metagenomes ([link](https://www.nature.com/articles/s41467-019-08844-4/figures/2)), you can see that we have good results.
mOTUs2 was also used in a recent paper to do a meta-analysis of colorectal cancer samples ([Wirbel et al. Nature medicine 2019](https://www.nature.com/articles/s41591-019-0406-6)), where they showed a strong association between cancer and microbial composition (profiled with mOTUs2).

**Comment by YaohuaYangVEC** [comment]
Thanks a lot!

For my two oral samples, yes, we did remove human reads.

Thanks!

Yaohua
