### ISSUE TITLE
tax level clarification

### ISSUE THREAD

**Issue by jzrapp** [motu-tool/mOTUs_v2#41]
Hi again! 

I have a quick question regarding the selection of tax level. Is it correct that this is a consensus taxonomy, and if I leave it at default level "species" , I will likely end up with fewer reads being classified than when changing it to class or phylum? Sorry, if this is obvious... I'm studying an environment for which I expect a big fraction of "unknown", and my test run resulted in ~65 classified species. Since I left it at relative abundance I don't know how many reads could be classified. Like this, it looks like 60% of the community is composed of the same species (which I doubt), so is it rather 60% of all the reads that could be assigned down to species level?
Thanks again!

**Comment by AlessioMilanese** [comment]
Hi @jzrapp ,

> Since I left it at relative abundance I don't know how many reads could be classified.

I would run with the `-c` option to have read counts instead of relative abundances.

So, mOTUs is basically mapping reads to 10 marker genes (MGs). These marker genes have the property of being universal and present in single-copy. By mapping the reads and taking the median read count across genes that belong to the same species, we have an evaluation of the cell counts per species:

![motus_profiling_framework](https://user-images.githubusercontent.com/16308111/68935193-8110b280-0798-11ea-87e2-35c5f69638e3.png)

**Comment by AlessioMilanese** [comment]
Note that since the MGs are universal, we can extract them also from metagenomic samples (meta-mOTUs).
Now, some considerations:
- we build the meta-mOTUs on Human associated biomes and Oceans, if you are profiling a sample that is not related to those (for example soil), then you will profile only ref-mOTUs and miss many of the unknown species.
- the reads that you use are only the ones that map to the 10MGs, so from all the metagenomic reads, you will use only ~2/3% for profiling. Which is fine for profiling.

**Comment by AlessioMilanese** [comment]
> Is it correct that this is a consensus taxonomy, and if I leave it at default level "species" , I will likely end up with fewer reads being classified than when changing it to class or phylum?

Actually, we map reads at species level. If you require phylum annotation (`-k phylum`), then we merge the read counts from species that are in the same phylum. This means that the read counts at species level and phylum level is exactly the same.


> I'm studying an environment for which I expect a big fraction of "unknown", and my test run resulted in ~65 classified species.

If it is not human associated or from ocean, then also mOTUs is missing some species. Note that we are still able to profile species that there are in NCBI (ref-mOTUs), and maybe some meta-mOTUs that were inferred from other environments. For example, if you are studying fresh water, it can be that some species are found also in Ocean (you might see some meta-mOTUs profiled).

One possible solution to study a new environment is to do something similar to what was done [here](https://www.nature.com/articles/s41564-017-0008-3): "We used COG0012 in our analyses,  since it has been demonstrated to be a robust universally conserved phylogenetic marker for near-species-level determinations".
Basically, it's similar to the mOTUs approach, but using one MG instead of 10 MGs. Basically:
1) create assemblies
2) run [fetchMG](https://github.com/motu-tool/fetchMGs), and extract the marker genes.
3) select only COG0012 genes
4) cluster them at 94.7% identity
5) you can map the reads to these clusters (which in a way represents mOTUs)
6) every cluster represents a species

Now you will be able to profile also species that are not present in the mOTUs database, and are specific for your samples.
Note that this approach can be complementary to construct MAGs (example [here](https://www.nature.com/articles/s41564-017-0012-7)), since you will retrieve many more COG0012 species clusters than MAGs.

> Like this, it looks like 60% of the community is composed of the same species (which I doubt), so is it rather 60% of all the reads that could be assigned down to species level?

It means 60% of the reads that map to the marker genes.

**Comment by jzrapp** [comment]
Thanks a lot, Alessio! This was helpful! I very much appreciate your support!
